export const MILLISECONDS_PER_SECOND = 1000
export const SECONDS_PER_MINUTE = 60
export const MINUTES_PER_HOUR = 60
export const HOURS_PER_DAY = 24
export const MILLISECONDS_PER_DAY =
  HOURS_PER_DAY * MINUTES_PER_HOUR * SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND

export const SESSION_TOKEN_BYTES = 32

export const DEFAULT_SESSION_DURATION_DAYS = 1
export const REMEMBER_ME_SESSION_DURATION_DAYS = 30

export const DEFAULT_SESSION_TTL_MS = DEFAULT_SESSION_DURATION_DAYS * MILLISECONDS_PER_DAY
export const REMEMBER_ME_SESSION_TTL_MS = REMEMBER_ME_SESSION_DURATION_DAYS * MILLISECONDS_PER_DAY

export const DEFAULT_SESSION_COOKIE_MAX_AGE_SECONDS =
  DEFAULT_SESSION_DURATION_DAYS * HOURS_PER_DAY * MINUTES_PER_HOUR * SECONDS_PER_MINUTE
export const REMEMBER_ME_SESSION_COOKIE_MAX_AGE_SECONDS =
  REMEMBER_ME_SESSION_DURATION_DAYS * HOURS_PER_DAY * MINUTES_PER_HOUR * SECONDS_PER_MINUTE

export const DEFAULT_SESSION_EXTENSION_DAYS = REMEMBER_ME_SESSION_DURATION_DAYS
