'use strict';

const REVENUE_FUNNEL_THRESHOLDS = {
  FUB_ACTIVATION_MIN: 0.2,
  AHA_COMPLETION_MIN: 0.3,
};

const REVENUE_METRICS_PROJECT_ID = 'leadflow';
const SPARKLINE_DAYS = 7;

module.exports = {
  REVENUE_FUNNEL_THRESHOLDS,
  REVENUE_METRICS_PROJECT_ID,
  SPARKLINE_DAYS,
};
