/**
 * E2E Test: fix-api-start-action-requires-sessionid-before-session
 * 
 * Tests the chicken-and-egg fix where the API start action was requiring
 * sessionId before the sessionId exists. The fix generates sessionId 
 * server-side for the start action.
 * 
 * Acceptance Criteria:
 * - AC-1: start action works WITHOUT sessionId (server generates one)
 * - AC-2: start action works WITH client-provided sessionId (backward compatible)
 * - AC-3: status action still REQUIRES sessionId
 * - AC-4: skip action still REQUIRES sessionId
 * - AC-5: sessionId is returned in the start response
 */

const assert = require('assert');
const http = require('http');

// Test configuration
const API_HOST = process.env.API_HOST || 'localhost';
const API_PORT = process.env.API_PORT || '3000';
const API_PATH = '/api/onboarding/simulator';

// Helper to make HTTP POST request
function makeRequest(body) {
  return new Promise((resolve, reject) => {
    const postData = JSON.stringify(body);
    
    const options = {
      hostname: API_HOST,
      port: API_PORT,
      path: API_PATH,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(postData),
      },
    };

    const req = http.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        try {
          resolve({
            status: res.statusCode,
            body: JSON.parse(data),
          });
        } catch (e) {
          resolve({
            status: res.statusCode,
            body: data,
          });
        }
      });
    });

    req.on('error', reject);
    req.write(postData);
    req.end();
  });
}

// Run tests
async function runTests() {
  const results = [];
  let passed = 0;
  let failed = 0;

  console.log('\n=== E2E Test: fix-api-start-action-requires-sessionid-before-session ===\n');

  // Test 1: AC-1 - start action works WITHOUT sessionId
  try {
    console.log('Test 1: AC-1 - start action works WITHOUT sessionId (server generates one)');
    const response = await makeRequest({
      action: 'start',
      agentId: 'test-agent-123',
      // No sessionId - this is the chicken-and-egg scenario
    });
    
    assert.strictEqual(response.status, 200, `Expected 200, got ${response.status}`);
    assert.strictEqual(response.body.success, true, 'Expected success to be true');
    assert.ok(response.body.state, 'Expected state in response');
    assert.ok(response.body.state.session_id, 'Expected session_id to be generated by server');
    assert.strictEqual(response.body.state.agent_id, 'test-agent-123', 'Expected agent_id to match');
    
    console.log('  ✓ PASS: Server generated sessionId:', response.body.state.session_id);
    results.push({ test: 'AC-1', status: 'PASS' });
    passed++;
  } catch (error) {
    console.log('  ✗ FAIL:', error.message);
    results.push({ test: 'AC-1', status: 'FAIL', error: error.message });
    failed++;
  }

  // Test 2: AC-2 - start action works WITH client-provided sessionId
  try {
    console.log('\nTest 2: AC-2 - start action works WITH client-provided sessionId (backward compatible)');
    const clientSessionId = 'client-session-' + Date.now();
    const response = await makeRequest({
      action: 'start',
      agentId: 'test-agent-456',
      sessionId: clientSessionId,
    });
    
    assert.strictEqual(response.status, 200, `Expected 200, got ${response.status}`);
    assert.strictEqual(response.body.success, true, 'Expected success to be true');
    assert.ok(response.body.state, 'Expected state in response');
    assert.strictEqual(response.body.state.session_id, clientSessionId, 'Expected session_id to match client-provided value');
    
    console.log('  ✓ PASS: Client sessionId preserved:', clientSessionId);
    results.push({ test: 'AC-2', status: 'PASS' });
    passed++;
  } catch (error) {
    console.log('  ✗ FAIL:', error.message);
    results.push({ test: 'AC-2', status: 'FAIL', error: error.message });
    failed++;
  }

  // Test 3: AC-3 - status action REQUIRES sessionId
  try {
    console.log('\nTest 3: AC-3 - status action REQUIRES sessionId');
    const response = await makeRequest({
      action: 'status',
      agentId: 'test-agent-789',
      // No sessionId - should fail
    });
    
    assert.strictEqual(response.status, 400, `Expected 400, got ${response.status}`);
    assert.ok(response.body.error, 'Expected error in response');
    assert.ok(response.body.error.includes('sessionId required'), `Expected "sessionId required" error, got: ${response.body.error}`);
    
    console.log('  ✓ PASS: status correctly requires sessionId');
    results.push({ test: 'AC-3', status: 'PASS' });
    passed++;
  } catch (error) {
    console.log('  ✗ FAIL:', error.message);
    results.push({ test: 'AC-3', status: 'FAIL', error: error.message });
    failed++;
  }

  // Test 4: AC-4 - skip action REQUIRES sessionId
  try {
    console.log('\nTest 4: AC-4 - skip action REQUIRES sessionId');
    const response = await makeRequest({
      action: 'skip',
      agentId: 'test-agent-abc',
      // No sessionId - should fail
    });
    
    assert.strictEqual(response.status, 400, `Expected 400, got ${response.status}`);
    assert.ok(response.body.error, 'Expected error in response');
    assert.ok(response.body.error.includes('sessionId required'), `Expected "sessionId required" error, got: ${response.body.error}`);
    
    console.log('  ✓ PASS: skip correctly requires sessionId');
    results.push({ test: 'AC-4', status: 'PASS' });
    passed++;
  } catch (error) {
    console.log('  ✗ FAIL:', error.message);
    results.push({ test: 'AC-4', status: 'FAIL', error: error.message });
    failed++;
  }

  // Test 5: AC-5 - status action works WITH sessionId
  try {
    console.log('\nTest 5: AC-5 - status action works WITH sessionId');
    // First start a simulation to get a sessionId
    const startResponse = await makeRequest({
      action: 'start',
      agentId: 'test-agent-def',
    });
    
    const sessionId = startResponse.body.state.session_id;
    
    // Now check status with the sessionId
    const statusResponse = await makeRequest({
      action: 'status',
      agentId: 'test-agent-def',
      sessionId: sessionId,
    });
    
    assert.strictEqual(statusResponse.status, 200, `Expected 200, got ${statusResponse.status}`);
    assert.ok(statusResponse.body.state, 'Expected state in response');
    assert.strictEqual(statusResponse.body.state.session_id, sessionId, 'Expected session_id to match');
    
    console.log('  ✓ PASS: status works with sessionId');
    results.push({ test: 'AC-5', status: 'PASS' });
    passed++;
  } catch (error) {
    console.log('  ✗ FAIL:', error.message);
    results.push({ test: 'AC-5', status: 'FAIL', error: error.message });
    failed++;
  }

  // Test 6: Edge case - missing action and agentId
  try {
    console.log('\nTest 6: Edge case - missing required fields');
    const response = await makeRequest({
      action: 'start',
      // No agentId
    });
    
    assert.strictEqual(response.status, 400, `Expected 400, got ${response.status}`);
    assert.ok(response.body.error, 'Expected error in response');
    
    console.log('  ✓ PASS: Correctly rejects missing agentId');
    results.push({ test: 'Edge case', status: 'PASS' });
    passed++;
  } catch (error) {
    console.log('  ✗ FAIL:', error.message);
    results.push({ test: 'Edge case', status: 'FAIL', error: error.message });
    failed++;
  }

  // Summary
  console.log('\n=== Test Summary ===');
  console.log(`Total: ${passed + failed}`);
  console.log(`Passed: ${passed}`);
  console.log(`Failed: ${failed}`);
  console.log(`Pass Rate: ${((passed / (passed + failed)) * 100).toFixed(1)}%`);
  
  if (failed > 0) {
    console.log('\nFailed tests:');
    results.filter(r => r.status === 'FAIL').forEach(r => {
      console.log(`  - ${r.test}: ${r.error}`);
    });
    process.exit(1);
  } else {
    console.log('\n✓ All tests passed!');
    process.exit(0);
  }
}

// Run tests if this file is executed directly
if (require.main === module) {
  runTests().catch(err => {
    console.error('Test runner error:', err);
    process.exit(1);
  });
}

module.exports = { runTests, makeRequest };
